### ISSUE TITLE
build on Mac OS X is broken since commit 55cdadd

### ISSUE THREAD

**Issue by thomasgi** [csete/gqrx#318]
When compiling GQRX on Mac OS X (10.9.5) using a macports environment following error occurs:

In file included from ../src/qtgui/dockrds.cpp:26:
./ui_dockrds.h:70:21: error: no member named 'setSizeAdjustPolicy' in 'QScrollArea'
        scrollArea->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContentsOnFirstShow);
        ~~~~~~~~~~  ^
./ui_dockrds.h:70:62: error: no member named 'AdjustToContentsOnFirstShow' in 'QAbstractScrollArea'
        scrollArea->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContentsOnFirstShow);
                                        ~~~~~~~~~~~~~~~~~~~~~^
2 errors generated.
make: *** [dockrds.o] Error 1


Macports uses QT 4.8.7-1, which does not have a method setSizeAdjustPolicy in QScrollArea or an enum QAbstractScrollArea::AdjustToContentsOnFirstShow according to the official QT 4.8 documentation.

**Comment by csete** [comment]
It should be fixed now, but let me know if it didn't work.

**Comment by thomasgi** [comment]
Yes, the problem is fixed now. Thank you for that super fast support.

Best regards
Thomas

Am 28.12.2015 um 18:37 schrieb Alexandru Csete <notifications@github.com>:
